 language: node_js
 node_js:
   - "0.10"
 before_install:
   - ./travis/build_step.py
 before_script:
   - npm install istanbul -g # code coverage tool
   - npm install coveralls -g # code coverage submitting
 script:
   - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
 after_success:
   - cat ./coverage/lcov.info | coveralls
